name: AI Question Processor
on:
  workflow_dispatch: # This adds a "Run" button in GitHub
  schedule:
    - cron: '0 */2 * * *' # Automatically runs every 2 hours

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install supabase requests google-generativeai pypdf

      - name: Run AI Processor
        run: python processor.py
